blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Questions & Discussion
    url: https://github.com/McIntosh-Lab/plspy/discussions
    about: Start here!
  - name: ğŸ“– Documentation
    url: https://plspy.readthedocs.io/en/latest/
    about: Official plspy documentation
  - name: â“ FAQ
    url: https://github.com/McIntosh-Lab/plspy/discussions/18
    about: Frequently Asked Questions
  - name: ğŸ’¡ Feature Requests
    url: https://github.com/McIntosh-Lab/plspy/discussions/new/choose
    about: Is plspy missing something?
  - name: ğŸ› ï¸ Support Requests
    url: https://github.com/McIntosh-Lab/plspy/discussions/new/choose
    about: Something not working? Having trouble with installation or running?
